"""add recurring transactions

Revision ID: 2c23836fde9a
Revises: d799e2ae1f02
Create Date: 2026-07-07 13:51:00.420431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c23836fde9a'
down_revision = 'd799e2ae1f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added so existing rows get a value — NOT NULL with no
    # default would fail against a table that already has data.
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('is_recurring', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
