"""add preview and updated_at to notes

Revision ID: 496646237e1d
Revises: 83fbc46bc76a
Create Date: 2026-07-10 00:25:28.106636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496646237e1d'
down_revision = '83fbc46bc76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('preview')

    # ### end Alembic commands ###
