"""add title and created_at to notes

Revision ID: 83fbc46bc76a
Revises: 2c23836fde9a
Create Date: 2026-07-07 22:01:19.103233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fbc46bc76a'
down_revision = '2c23836fde9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        # server_default backfills existing rows with the current timestamp
        # instead of leaving created_at NULL (which would break
        # note.created_at.strftime(...) in the notes page template).
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
