"""add scenarios

Revision ID: d799e2ae1f02
Revises: b8bdd1dab22f
Create Date: 2026-07-06 16:26:11.711064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd799e2ae1f02'
down_revision = 'b8bdd1dab22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('one_time_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('emotional_value', sa.Integer(), nullable=False),
    sa.Column('financial_risk', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_user_id'))
        batch_op.drop_index(batch_op.f('ix_scenario_status'))

    op.drop_table('scenario')
    # ### end Alembic commands ###
